# Generated by Django 5.2.1 on 2026-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='game_api_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
