# Generated by Django 5.2.1 on 2026-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_api_token_and_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='game_api_callback_url',
            field=models.URLField(blank=True),
        ),
    ]
