# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game_api_domain_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='game_api_launch_url',
            field=models.URLField(blank=True),
        ),
    ]
