# Generated by Django 5.2.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_api_launch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='status',
            field=models.CharField(
                choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')],
                default='pending',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='action_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payment_modes_acted_on',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name='paymentmode',
            name='is_active',
        ),
    ]
