# Generated by Django 5.2.1

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentmode_status_and_verification'),
    ]

    operations = [
        migrations.RemoveField(model_name='user', name='kyc_approved_by'),
        migrations.RemoveField(model_name='user', name='kyc_document'),
        migrations.RemoveField(model_name='user', name='kyc_reject_reason'),
        migrations.RemoveField(model_name='user', name='kyc_status'),
    ]
