# Generated by Django 6.0.2 on 2026-02-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersetting',
            name='default_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
