# Generated by Django 6.0.2 on 2026-02-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_game_coming_soon_fields'),
        ('core', '0018_alter_supersetting_default_master'),
    ]

    operations = [
    ]
