# Generated by Django 6.0.2 on 2026-03-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_withdraw_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelog',
            options={'verbose_name': 'Bet History', 'verbose_name_plural': 'Bet History'},
        ),
    ]
