# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_gamelog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderslide',
            name='cta_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='cta_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
