# Generated by Django 6.0.2 on 2026-03-25 15:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_user_whatsapp_deposit_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersetting',
            name='reject_reason_suggestions',
            field=models.JSONField(blank=True, default=core.models.default_reject_reason_suggestions),
        ),
    ]
