from django.urls import path
from core.views.powerhouse import (
    country_views,
    dashboard_views,
    user_views,
    deposit_views,
    withdraw_views,
    bonus_request_views,
    game_log_views,
    transaction_views,
    activity_views,
    accounting_views,
    game_views,
    game_import_views,
    super_setting_views,
    site_setting_views,
    slider_views,
    popup_views,
    promotion_views,
    coming_soon_enrollment_views,
    live_betting_views,
    cms_views,
    testimonial_views,
    message_views,
    bonus_rule_views,
    payment_mode_verification_views,
    me_views,
    payment_method_views,
)
from core.views.super import statement_views as super_statement_views
from core.views.super import report_views as super_report_views

urlpatterns = [
    path('dashboard/', dashboard_views.dashboard),
    path('supers/', user_views.user_list_supers),
    path('supers/<int:pk>/', user_views.user_detail_supers),
    path('supers/create/', user_views.user_create_super),
    path('supers/<int:pk>/edit/', user_views.user_update_super),
    path('supers/<int:pk>/delete/', user_views.user_delete_super),
    path('supers/<int:pk>/regenerate-pin/', user_views.user_regenerate_pin_super),
    path('supers/<int:pk>/reset-password/', user_views.user_reset_password_super),
    path('masters/', user_views.user_list_masters),
    path('masters/<int:pk>/', user_views.user_detail_masters),
    path('masters/create/', user_views.user_create_master),
    path('masters/<int:pk>/edit/', user_views.user_update_master),
    path('masters/<int:pk>/delete/', user_views.user_delete_master),
    path('masters/<int:pk>/regenerate-pin/', user_views.user_regenerate_pin_master),
    path('masters/<int:pk>/reset-password/', user_views.user_reset_password_master),
    path('players/', user_views.user_list_players),
    path('players/<int:pk>/', user_views.user_detail_players),
    path('players/<int:pk>/report/', user_views.player_report),
    path('players/create/', user_views.user_create_player),
    path('players/<int:pk>/edit/', user_views.user_update_player),
    path('players/<int:pk>/toggle-active/', user_views.user_toggle_active_player),
    path('players/<int:pk>/delete/', user_views.user_delete_player),
    path('players/<int:pk>/regenerate-pin/', user_views.user_regenerate_pin_player),
    path('players/<int:pk>/reset-password/', user_views.user_reset_password_player),
    path('deposits/', deposit_views.deposit_list),
    path('deposits/create/', deposit_views.deposit_create),
    path('deposits/direct/', deposit_views.deposit_direct),
    path('deposits/payment-modes/', deposit_views.deposit_payment_modes),
    path('deposits/<int:pk>/', deposit_views.deposit_detail),
    path('deposits/<int:pk>/approve/', deposit_views.deposit_approve),
    path('deposits/<int:pk>/reject/', deposit_views.deposit_reject),
    path('withdrawals/', withdraw_views.withdraw_list),
    path('withdrawals/direct/', withdraw_views.withdraw_direct),
    path('withdrawals/<int:pk>/', withdraw_views.withdraw_detail),
    path('withdrawals/<int:pk>/approve/', withdraw_views.withdraw_approve),
    path('withdrawals/<int:pk>/reject/', withdraw_views.withdraw_reject),
    path('bonus-requests/', bonus_request_views.bonus_request_list),
    path('bonus-requests/<int:pk>/', bonus_request_views.bonus_request_detail),
    path('bonus-requests/<int:pk>/approve/', bonus_request_views.bonus_request_approve),
    path('bonus-requests/<int:pk>/reject/', bonus_request_views.bonus_request_reject),
    path('game-log/', game_log_views.game_log_list),
    path('game-log/<int:pk>/', game_log_views.game_log_detail),
    path('transactions/', transaction_views.transaction_list),
    path('accounting-report/', accounting_views.accounting_report),
    path('account-statement/', super_statement_views.account_statement_list),
    path('bonus-statement/', super_statement_views.bonus_statement_list),
    path('client-request/total-dw/', super_report_views.total_dw_list),
    path('client-request/super-master-dw/', super_report_views.super_master_dw_list),
    path('client-request/super-dw-state/', super_report_views.super_dw_state_list),
    path('activity/', activity_views.activity_list),
    path('categories/', game_views.category_list_create),
    path('categories/<int:pk>/', game_views.category_detail),
    path('providers/', game_views.provider_list_create),
    path('providers/<int:pk>/', game_views.provider_detail),
    path('games/', game_views.game_list_create),
    path('games/<int:pk>/', game_views.game_detail),
    path('import/game-api-url/', game_import_views.import_game_api_url),
    path('import/games/', game_import_views.import_games_create),
    path('bonus-rules/', bonus_rule_views.bonus_rule_list_create),
    path('bonus-rules/<int:pk>/', bonus_rule_views.bonus_rule_detail),
    path('super-settings/', super_setting_views.super_setting_get),
    path('super-settings/save/', super_setting_views.super_setting_save),
    path('site-settings/', site_setting_views.site_setting_get),
    path('site-settings/update/', site_setting_views.site_setting_update),
    path('upload-site-media/', site_setting_views.upload_site_media),
    path('slider/', slider_views.slider_list_create),
    path('slider/<int:pk>/', slider_views.slider_detail),
    path('popup/', popup_views.popup_list_create),
    path('popup/<int:pk>/', popup_views.popup_detail),
    path('promotions/', promotion_views.promotion_list_create),
    path('promotions/<int:pk>/', promotion_views.promotion_detail),
    path('coming-soon-enrollments/', coming_soon_enrollment_views.coming_soon_enrollment_list),
    path('live-betting-sections/', live_betting_views.live_betting_section_list_create),
    path('live-betting-sections/<int:pk>/', live_betting_views.live_betting_section_detail),
    path('live-betting-events/', live_betting_views.live_betting_event_list_create),
    path('live-betting-events/<int:pk>/', live_betting_views.live_betting_event_detail),
    path('cms/', cms_views.cms_list_create),
    path('cms/<int:pk>/', cms_views.cms_detail),
    path('testimonials/', testimonial_views.testimonial_list_create),
    path('testimonials/<int:pk>/', testimonial_views.testimonial_detail),
    path('messages/', message_views.message_list),
    path('messages/contacts/', message_views.message_contacts),
    path('messages/unread-count/', message_views.message_unread_count),
    path('messages/send/', message_views.message_create),
    path('payment-mode-verification/', payment_mode_verification_views.payment_mode_verification_list),
    path('payment-mode-verification/<int:pk>/approve/', payment_mode_verification_views.payment_mode_approve),
    path('payment-mode-verification/<int:pk>/reject/', payment_mode_verification_views.payment_mode_reject),
    path('profile/', me_views.profile_get),
    path('profile/update/', me_views.profile_update),
    path('change-password/', me_views.change_password),
    path('payment-methods/', payment_method_views.payment_method_list_create),
    path('payment-methods/<int:pk>/', payment_method_views.payment_method_detail),
    path('countries/', country_views.country_list_create),
    path('countries/<int:pk>/', country_views.country_detail),
]
