from django.urls import path
from core.views.super import (
    dashboard_views,
    user_views,
    deposit_views,
    withdraw_views,
    bonus_request_views,
    game_log_views,
    transaction_views,
    activity_views,
    message_views,
    settlement_views,
    payment_mode_verification_views,
    me_views,
    accounting_views,
    statement_views,
    report_views,
)

urlpatterns = [
    path('dashboard/', dashboard_views.dashboard),
    path('masters/', user_views.master_list),
    path('masters/<int:pk>/', user_views.master_detail),
    path('masters/create/', user_views.master_create),
    path('masters/<int:pk>/edit/', user_views.master_update),
    path('masters/<int:pk>/delete/', user_views.master_delete),
    path('masters/<int:pk>/regenerate-pin/', user_views.master_regenerate_pin),
    path('masters/<int:pk>/reset-password/', user_views.master_reset_password),
    path('players/', user_views.player_list),
    path('players/<int:pk>/', user_views.player_detail),
    path('players/<int:pk>/report/', user_views.player_report),
    path('players/create/', user_views.player_create),
    path('players/<int:pk>/edit/', user_views.player_update),
    path('players/<int:pk>/toggle-active/', user_views.player_toggle_active),
    path('players/<int:pk>/delete/', user_views.player_delete),
    path('players/<int:pk>/regenerate-pin/', user_views.player_regenerate_pin),
    path('players/<int:pk>/reset-password/', user_views.player_reset_password),
    path('deposits/', deposit_views.deposit_list),
    path('deposits/create/', deposit_views.deposit_create),
    path('deposits/direct/', deposit_views.deposit_direct),
    path('deposits/payment-modes/', deposit_views.deposit_payment_modes),
    path('deposits/<int:pk>/', deposit_views.deposit_detail),
    path('deposits/<int:pk>/approve/', deposit_views.deposit_approve),
    path('deposits/<int:pk>/reject/', deposit_views.deposit_reject),
    path('withdrawals/', withdraw_views.withdraw_list),
    path('withdrawals/direct/', withdraw_views.withdraw_direct),
    path('withdrawals/<int:pk>/', withdraw_views.withdraw_detail),
    path('withdrawals/<int:pk>/approve/', withdraw_views.withdraw_approve),
    path('withdrawals/<int:pk>/reject/', withdraw_views.withdraw_reject),
    path('bonus-requests/', bonus_request_views.bonus_request_list),
    path('bonus-requests/<int:pk>/', bonus_request_views.bonus_request_detail),
    path('bonus-requests/<int:pk>/approve/', bonus_request_views.bonus_request_approve),
    path('bonus-requests/<int:pk>/reject/', bonus_request_views.bonus_request_reject),
    path('game-log/', game_log_views.game_log_list),
    path('game-log/<int:pk>/', game_log_views.game_log_detail),
    path('transactions/', transaction_views.transaction_list),
    path('accounting-report/', accounting_views.accounting_report),
    path('account-statement/', statement_views.account_statement_list),
    path('bonus-statement/', statement_views.bonus_statement_list),
    path('client-request/total-dw/', report_views.total_dw_list),
    path('client-request/super-master-dw/', report_views.super_master_dw_list),
    path('client-request/super-dw-state/', report_views.super_dw_state_list),
    path('payment-method/', payment_mode_verification_views.payment_mode_verification_list),
    path('activity/', activity_views.activity_list),
    path('messages/', message_views.message_list),
    path('messages/contacts/', message_views.message_contacts),
    path('messages/unread-count/', message_views.message_unread_count),
    path('messages/send/', message_views.message_create),
    path('settlement/<int:pk>/', settlement_views.settle),
    path('payment-mode-verification/', payment_mode_verification_views.payment_mode_verification_list),
    path('payment-mode-verification/<int:pk>/approve/', payment_mode_verification_views.payment_mode_approve),
    path('payment-mode-verification/<int:pk>/reject/', payment_mode_verification_views.payment_mode_reject),
    path('profile/', me_views.profile_get),
    path('profile/update/', me_views.profile_update),
    path('change-password/', me_views.change_password),
]
